blank_issues_enabled: false
contact_links:
  - name: Code of Conduct
    url: https://github.com/GrayGalaxy/graygalaxy/blob/main/code_of_conduct.md
    about: Follow the community guidlines before posring